language: node_js
node_js:
    - 0.11
before_script:
    - npm install -g grunt-cli
notifications:
    irc:
        channels:
            - "irc.barafranca.com#dev"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
        skip_join: true
